### ISSUE TITLE
where can I download the data files?

### ISSUE THREAD

**Issue by rongzhou** [tspooner/rl_markets#4]
Failed to run it without data, Is it possible to get the original data files? Thanks in advance.

**Comment by tspooner** [comment]
Hey rongzhou. So this work is about how one can derive strategies directly from data. Unfortunately, I can't give you access to ours as it's very expensive and under strict requirements about sharing.

Sorry about that.

**Comment by tspooner** [comment]
You will need to source your own L2 data (or better) and code up a parser to integrate in the existing codebase.

**Comment by mbasso** [comment]
Hi @rongzhou,
have you found a solution for this?
I'm currently searching for a dataset too
