### ISSUE TITLE
make error (Mac OSX)

### ISSUE THREAD

**Issue by dichen9412** [tspooner/rl_markets#7]
MacBook-Pro-10:build chendi$ make 
[  1%] Performing update step for 'catch'
Already up to date.
[  3%] No configure step for 'catch'
[  5%] No build step for 'catch'
[  7%] No install step for 'catch'
[  9%] Completed 'catch'
[ 14%] Built target catch
[ 16%] Performing update step for 'yaml-cpp'
Already up to date.
[ 18%] Performing configure step for 'yaml-cpp'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/chendi/Desktop/Cornell/intern/IBM 2019/BlueStarTradingZoo/market_making_via_RL_code/rl_markets/build/ext/yaml-cpp/src/yaml-cpp-build
[ 20%] Performing build step for 'yaml-cpp'
[ 59%] Built target yaml-cpp
[ 75%] Built target googletest_project
[100%] Built target run-tests
[ 22%] No install step for 'yaml-cpp'
[ 24%] Completed 'yaml-cpp'
[ 29%] Built target yaml-cpp
[ 31%] Performing update step for 'spdlog'
Already up to date.
[ 33%] No configure step for 'spdlog'
[ 35%] No build step for 'spdlog'
[ 37%] No install step for 'spdlog'
[ 38%] Completed 'spdlog'
[ 44%] Built target spdlog
make[2]: *** No rule to make target `ext/yaml-cpp/src/yaml-cpp-build/libyaml-cpp.so', needed by `librl_engine.dylib'.  Stop.
make[1]: *** [src/CMakeFiles/rl_engine.dir/all] Error 2
make: *** [all] Error 2

I tried to fix the previous error about "make_unique" and ended up having this error. 
I tried to search it online but found nothing. Can you help me make this work?

Best,
Di

**Comment by fluxArch** [comment]
How did you fix it? I would really appreciate it!
