### ISSUE TITLE
theta_b of Class DoubleAgent unused?

### ISSUE THREAD

**Issue by stephenkgu** [tspooner/rl_markets#9]
hi, first thanks for this great work.

getQ(s, a) and getQb(s, a) both use theta data, leave theta_b unused, is this correct?

I did not find any correspond DoubleAgent in project rsrl to reference too. @tspooner

**Comment by tspooner** [comment]
Hi Stephen,

Glad you got something from it! You are indeed right, there appears to be an error in that code. Interestingly, this must have been introduced when I re-factored the code for a public version as it doesn't appear in my original source. The DoubleAgent should use theta_b in the getQb function.

I'll push a change for this immediately, so thanks for the spot!

Indeed, I haven't implemented this in rsrl yet, but will get around to it ASAP.

Cheers,
Tom

**Comment by tspooner** [comment]
See commit: 2de4cbb0936dd01cf5611e457f7bc2453403ef7d
